### PR TITLE
[Pre-contest] Exercise 3 in Rust.

### PR DESCRIPTION
**Pull request by totorigolo**
Exercise 3 in Rust.

### CODE REVIEW

**Comment by Nyrio** [comment]
Your solution is correct and efficient.

**Comment by Nyrio** [comment]
However, can you please add some comments like in the other solutions ?

**Comment by totorigolo** [comment]
I ended writing longer comments than in the other solutions :grin: Tell me if you spot anything wrong.

**Comment by Nyrio** [comment]
Thanks for all the great comments. Fixed a few typos. The solution is passing the tests. I still trust you on the code.

**Pull request merged**
